# See the dedicated "version" documentation section.
version: "2"
linters:
  default: all
  disable:
    - cyclop
    - dupl
    - err113
    - errchkjson
    - errname
    - exhaustive
    - exhaustruct
    - funlen
    - funcorder
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godoclint
    - inamedparam
    - intrange
    - ireturn
    - maintidx
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - revive
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          # List of allowed packages.
          # Entries can be a variable (starting with $), a string prefix, or an exact match (if ending with $).
          # Default: []
          allow:
            - $gostd
            - github.com/stretchr/testify
            - github.com/moogar0880/venom
          deny: []
    modernize:
      disable:
        - any
        - rangeint
        - reflecttypefor
