//+build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"strings"
)

const packageHdr = `
// Code generated by "go run generate_coercers.go"; DO NOT EDIT.
package venom
`

const pkgImports = `
import "fmt"

`

const coerceErr = `
// A CoerceErr is returned when incompatible types are attempted to be coerced
type CoerceErr struct{
	From interface{}
	To string
}

func (e *CoerceErr) Error() string {
	return fmt.Sprintf("venom: can not coerce %T to %q", e.From, e.To)
}

`

const packageIntro = packageHdr + pkgImports + coerceErr

var (
	types = []reflect.Kind{
		reflect.String,
		reflect.Bool,
		reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32,
		reflect.Uint64,
		reflect.Float32, reflect.Float64,
		// "struct",
		// "slice",
	}

	kindToType = map[reflect.Kind]reflect.Type{
		reflect.String:  reflect.TypeOf(""),
		reflect.Bool:    reflect.TypeOf(true),
		reflect.Int:     reflect.TypeOf(int(0)),
		reflect.Int8:    reflect.TypeOf(int8(0)),
		reflect.Int16:   reflect.TypeOf(int16(0)),
		reflect.Int32:   reflect.TypeOf(int32(0)),
		reflect.Int64:   reflect.TypeOf(int64(0)),
		reflect.Uint:    reflect.TypeOf(uint(0)),
		reflect.Uint8:   reflect.TypeOf(uint8(0)),
		reflect.Uint16:  reflect.TypeOf(uint16(0)),
		reflect.Uint32:  reflect.TypeOf(uint32(0)),
		reflect.Uint64:  reflect.TypeOf(uint64(0)),
		reflect.Float32: reflect.TypeOf(float32(0.0)),
		reflect.Float64: reflect.TypeOf(float64(0.0)),
	}
)

func zeroValue(k reflect.Kind) interface{} {
	return reflect.Zero(kindToType[k]).Interface()
}

func kindTitle(k reflect.Kind) string {
	return strings.Replace(
		k.String(),
		string(k.String()[0]),
		strings.ToUpper(string(k.String()[0])),
		-1,
	)
}

func writeCaster(to reflect.Kind) string {
	zeroValFmt := "%v"
	if to == reflect.String {
		zeroValFmt = "%q"
	}
	return fmt.Sprintf(`if value, ok := val.(%s); !ok {
		return `+zeroValFmt+`, &CoerceErr{val, %q}
	} else {
		return value, nil
	}
`, to, zeroValue(to), to)
}

func writeSliceCaster(to reflect.Kind) string {
	return fmt.Sprintf(`if value, ok := val.([]%s); !ok {
		return nil, &CoerceErr{val, "[]%s"}
	} else {
		return value, nil
	}
`, to, to)
}

func writeCoercers(buff *bytes.Buffer) error {
	buff.WriteString(packageIntro)

	for _, typ := range types {
		fmt.Fprintf(buff, "func coerce%s(val interface{}) (%s, error) {\n\t", kindTitle(typ), typ.String())
		fmt.Fprintf(buff, writeCaster(typ)+"}\n\n")

		fmt.Fprintf(buff, "func coerce%sSlice(val interface{}) ([]%s, error) {\n\t", kindTitle(typ), typ.String())
		fmt.Fprintf(buff, writeSliceCaster(typ)+"}\n\n")
	}

	// gofmt
	res, err := format.Source(buff.Bytes())
	if err != nil {
		fmt.Println(buff.String())
		panic(err.Error())
	}

	// write result
	f, err := os.Create("coercers.go")
	if err != nil {
		panic(err.Error())
	}
	defer f.Close()
	f.Write(res)
	return nil
}

func writeCoercerTests(buff *bytes.Buffer) error {
	buff.WriteString(packageHdr)
	return nil
}

func main() {
	coercersBuff := new(bytes.Buffer)
	coercersTestBuff := new(bytes.Buffer)

	writeCoercers(coercersBuff)
	writeCoercerTests(coercersTestBuff)
}
